/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Controle.ProdutoControle;
import Modelo.ProdutoModelo;
import ferramentas.LimparCampos;
import ferramentas.PreencherJtableGenerico;
import ferramentas.Rotinas;
import javax.swing.JOptionPane;

/**
 * @author junio
 */
public class Produto extends javax.swing.JFrame {
   private ProdutoControle daoproduto = new ProdutoControle();
    private ProdutoModelo modproduto = new ProdutoModelo();
    
    private PreencherJtableGenerico preencher = new PreencherJtableGenerico();
    LimparCampos limpar = new LimparCampos();
    private int estado;
    
    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
        estadobotoes(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbPainel = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jBCancelar = new javax.swing.JToggleButton();
        jBGravar = new javax.swing.JToggleButton();
        jBExcluir = new javax.swing.JToggleButton();
        jBAlterar = new javax.swing.JToggleButton();
        jBNovo = new javax.swing.JToggleButton();
        jTFCodigoProduto = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFNomeProduto = new javax.swing.JTextField();
        jLDrecricao = new javax.swing.JLabel();
        jTFAroProduto = new javax.swing.JTextField();
        jTFDescricaoProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFModeloProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFValorProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFMarchasProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCategoriaProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPCasulta = new javax.swing.JPanel();
        jCbTipo = new javax.swing.JComboBox<>();
        jTFPesquisarProduto = new javax.swing.JTextField();
        jBPesquisarProduto = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbConsulta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GLG Bikes");

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jTFCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoProdutoActionPerformed(evt);
            }
        });

        jLCodigo.setText("Código");

        jLabel1.setText("Nome Produto");

        jTFNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeProdutoActionPerformed(evt);
            }
        });

        jLDrecricao.setText("Descrição Produto");

        jTFAroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAroProdutoActionPerformed(evt);
            }
        });

        jTFDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescricaoProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        jTFModeloProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFModeloProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Aro");

        jTFValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFValorProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Marchas");

        jTFMarchasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMarchasProdutoActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor");

        jTFCategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCategoriaProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText("Categoria");

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jTFCategoriaProduto)
                        .addContainerGap())
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCodigo)
                                    .addComponent(jTFCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(333, 333, 333)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jTFAroProduto))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jTFMarchasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTFNomeProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFModeloProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTFValorProduto))))
                        .addContainerGap())
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLDrecricao))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFModeloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFAroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFMarchasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDrecricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jTbPainel.addTab("Cadastro", jPCadastro);

        jCbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Código", "Nome", "Modelo", "Aro", "Marchas", "Valor", "Categoria", "Descrição" }));
        jCbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTipoActionPerformed(evt);
            }
        });

        jTFPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarProdutoActionPerformed(evt);
            }
        });

        jBPesquisarProduto.setText("Pesquisar");
        jBPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarProdutoActionPerformed(evt);
            }
        });

        jTbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome Produto", "Modelo", "Aro", "Marchas", "Valor", "Descrição", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbConsulta);

        javax.swing.GroupLayout jPCasultaLayout = new javax.swing.GroupLayout(jPCasulta);
        jPCasulta.setLayout(jPCasultaLayout);
        jPCasultaLayout.setHorizontalGroup(
            jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addGroup(jPCasultaLayout.createSequentialGroup()
                        .addComponent(jCbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFPesquisarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisarProduto)))
                .addContainerGap())
        );
        jPCasultaLayout.setVerticalGroup(
            jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTbPainel.addTab("Consulta", jPCasulta);

        jMenuAjuda.setText("Ajuda");
        jMenuBar1.add(jMenuAjuda);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFAroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAroProdutoActionPerformed

    private void jTFNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeProdutoActionPerformed

    private void jTFCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoProdutoActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
      
        estado = Rotinas.INCLUIR;
        estadobotoes (1);
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
       
        estado = Rotinas.ALTERAR;
        estadobotoes (1);
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
         if (jTFNomeProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um registro a ser excluido");
            return;
        } else {
            setcomp();
            daoproduto.excluir(modproduto);
            jTFCodigoProduto.setText("");
            jTFNomeProduto.setText("");
            jTFModeloProduto.setText("");
            jTFAroProduto.setText("");
            jTFMarchasProduto.setText("");
            jTFValorProduto.setText("");
            jTFCategoriaProduto.setText("");
            jTFDescricaoProduto.setText("");
        
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
         estadobotoes(0);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTipoActionPerformed

    private void jBPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        preencher.FormatarJtable(jTbConsulta, new int[]{10, 75, 75, 10, 10, 15, 300, 300});

        switch (jCbTipo.getSelectedIndex()) {
            case 0: {
                preencher.PreencherJtableGenerico(jTbConsulta,
                        new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultageral());
                break;
            } 
            case 1: {
                modproduto.setIdproduto(Integer.parseInt(jTFPesquisarProduto.getText()));
                preencher.PreencherJtableGenerico(jTbConsulta,
                        new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultaid(modproduto));
                break;
            }
            case 2: {
                modproduto.setNome(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultanome(modproduto));
                break;
            }
            case 3: {
                modproduto.setModelo(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultamodelo (modproduto));
                break;
            }
            case 4: {
                 modproduto.setAro(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultaaro(modproduto));
                break;
            }
            case 5: {
                modproduto.setMarchas(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultamarchas(modproduto));
                break;
            }
             case 6: {
                 modproduto.setValor(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultavalor(modproduto));
                break;
            }
               case 7: {
                modproduto.setDescricao(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultadescricao(modproduto));
                break;
            }
               case 8: {
                modproduto.setCategoria(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_produto", "nome","modelo","aro", "marchas","valor","descricao", "categoria"},
                        daoproduto.consultacategoria(modproduto));
                break;
            }
        }
    }//GEN-LAST:event_jBPesquisarProdutoActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        // TODO add your handling code here:
          if (jTFNomeProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Descrição Obrigatoria");
            jTFNomeProduto.grabFocus();
            return;
        } else {

            setcomp();
            if (estado == Rotinas.INCLUIR) {
                daoproduto.incluir(modproduto);
            } else if (estado == Rotinas.ALTERAR) {
                daoproduto.alterar(modproduto);
            }
            getcomp();
            estadobotoes(0);
        }
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jTFPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarProdutoActionPerformed

    private void jTbConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbConsultaMouseClicked
        
        if (evt.getClickCount() == 2) {
          int linha = jTbConsulta.getSelectedRow();
          
          String codigo = (String) jTbConsulta.getValueAt(linha, 0);
          modproduto.setIdproduto(Integer.parseInt(codigo));
          daoproduto.retornadados(modproduto);
          getcomp();
          jTbPainel.setSelectedIndex(0);
      }
    }//GEN-LAST:event_jTbConsultaMouseClicked

    private void jTFDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescricaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescricaoProdutoActionPerformed

    private void jTFModeloProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFModeloProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFModeloProdutoActionPerformed

    private void jTFValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFValorProdutoActionPerformed

    private void jTFMarchasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMarchasProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMarchasProdutoActionPerformed

    private void jTFCategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCategoriaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCategoriaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBAlterar;
    private javax.swing.JToggleButton jBCancelar;
    private javax.swing.JToggleButton jBExcluir;
    private javax.swing.JToggleButton jBGravar;
    private javax.swing.JToggleButton jBNovo;
    private javax.swing.JToggleButton jBPesquisarProduto;
    private javax.swing.JComboBox<String> jCbTipo;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDrecricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPCasulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAroProduto;
    private javax.swing.JTextField jTFCategoriaProduto;
    private javax.swing.JTextField jTFCodigoProduto;
    private javax.swing.JTextField jTFDescricaoProduto;
    private javax.swing.JTextField jTFMarchasProduto;
    private javax.swing.JTextField jTFModeloProduto;
    private javax.swing.JTextField jTFNomeProduto;
    private javax.swing.JTextField jTFPesquisarProduto;
    private javax.swing.JTextField jTFValorProduto;
    private javax.swing.JTable jTbConsulta;
    private javax.swing.JTabbedPane jTbPainel;
    // End of variables declaration//GEN-END:variables

    private void estadobotoes(int situacao) {
      if (situacao == 0) {
            jBNovo.setEnabled(true);
            jBAlterar.setEnabled(true);
            jBExcluir.setEnabled(true);
            jBGravar.setEnabled(false);
            jBCancelar.setEnabled(false);
        } else {
            jBNovo.setEnabled(false);
            jBAlterar.setEnabled(false);
            jBExcluir.setEnabled(false);
            jBGravar.setEnabled(true);
            jBCancelar.setEnabled(true);
        }
    }

    private void setcomp() {
       if (estado == Rotinas.ALTERAR) {
            modproduto.setIdproduto(Integer.parseInt(jTFCodigoProduto.getText()));
        }
        modproduto.setNome(jTFNomeProduto.getText());
        modproduto.setModelo(jTFModeloProduto.getText());
        modproduto.setAro(jTFAroProduto.getText());
        modproduto.setMarchas(jTFMarchasProduto.getText());
        modproduto.setValor(jTFValorProduto.getText());
        modproduto.setDescricao(jTFDescricaoProduto.getText());
        modproduto.setCategoria(jTFCategoriaProduto.getText());
       
    }

    private void getcomp() {
        jTFCodigoProduto.setText(Integer.toString(modproduto.getIdproduto()));
        jTFNomeProduto.setText(modproduto.getNome());
        jTFModeloProduto.setText(modproduto.getModelo());
        jTFAroProduto.setText(modproduto.getAro());
        jTFMarchasProduto.setText(modproduto.getMarchas());
        jTFValorProduto.setText(modproduto.getValor());
        jTFDescricaoProduto.setText(modproduto.getDescricao());
        jTFCategoriaProduto.setText(modproduto.getCategoria());
    }
}
