/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Controle.ProdutoControle;
import Modelo.ProdutoModelo;
import ferramentas.LimparCampos;
import ferramentas.PreencherJtableGenerico;
import ferramentas.Rotinas;
import javax.swing.JOptionPane;

/**
 *
 * @author junio
 */
public class Produto extends javax.swing.JFrame {
   private ProdutoControle daoproduto = new ProdutoControle();
    private ProdutoModelo modproduto = new ProdutoModelo();
    
    private PreencherJtableGenerico preencher = new PreencherJtableGenerico();
    LimparCampos limpar = new LimparCampos();
    private int estado;
    
    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
        estadobotoes(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbPainel = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jBCancelar = new javax.swing.JToggleButton();
        jBGravar = new javax.swing.JToggleButton();
        jBExcluir = new javax.swing.JToggleButton();
        jBAlterar = new javax.swing.JToggleButton();
        jBNovo = new javax.swing.JToggleButton();
        jTFCodigoProduto = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFNomeProduto = new javax.swing.JTextField();
        jLDrecricao = new javax.swing.JLabel();
        jTFDescricaoProduto = new javax.swing.JTextField();
        jPCasulta = new javax.swing.JPanel();
        jCbTipo = new javax.swing.JComboBox<>();
        jTFPesquisarProduto = new javax.swing.JTextField();
        jBPesquisarProduto = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbConsulta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Produto");

        jBCancelar.setText("CANCELAR");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBGravar.setText("GRAVAR");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });

        jBExcluir.setText("EXCLUIR");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("ALTERAR");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBNovo.setText("NOVO");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jTFCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoProdutoActionPerformed(evt);
            }
        });

        jLCodigo.setText("Código");

        jLabel1.setText("Nome Produto");

        jTFNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeProdutoActionPerformed(evt);
            }
        });

        jLDrecricao.setText("Drecrição Produto");

        jTFDescricaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescricaoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCodigo)
                                    .addComponent(jTFCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLDrecricao))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTFNomeProduto)
                            .addComponent(jTFDescricaoProduto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDrecricao)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );

        jTbPainel.addTab("Cadastro", jPCadastro);

        jCbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Código", "Nome", "Descrição" }));
        jCbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTipoActionPerformed(evt);
            }
        });

        jTFPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarProdutoActionPerformed(evt);
            }
        });

        jBPesquisarProduto.setText("Pesquisar");
        jBPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarProdutoActionPerformed(evt);
            }
        });

        jTbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome Produto", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbConsulta);

        javax.swing.GroupLayout jPCasultaLayout = new javax.swing.GroupLayout(jPCasulta);
        jPCasulta.setLayout(jPCasultaLayout);
        jPCasultaLayout.setHorizontalGroup(
            jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addGroup(jPCasultaLayout.createSequentialGroup()
                        .addComponent(jCbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFPesquisarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisarProduto)))
                .addContainerGap())
        );
        jPCasultaLayout.setVerticalGroup(
            jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCasultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTbPainel.addTab("Consulta", jPCasulta);

        jMenuAjuda.setText("Ajuda");
        jMenuBar1.add(jMenuAjuda);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDescricaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescricaoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescricaoProdutoActionPerformed

    private void jTFNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeProdutoActionPerformed

    private void jTFCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoProdutoActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
      
        estado = Rotinas.INCLUIR;
        estadobotoes (1);
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
       
        estado = Rotinas.ALTERAR;
        estadobotoes (1);
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
         if (jTFNomeProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um registro a ser excluido");
            return;
        } else {
            setcomp();
            daoproduto.excluir(modproduto);
            jTFCodigoProduto.setText("");
            jTFNomeProduto.setText("");
            jTFCodigoProduto.setText("");
        
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
         estadobotoes(0);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTipoActionPerformed

    private void jBPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        preencher.FormatarJtable(jTbConsulta, new int[]{150, 50, 200});

        switch (jCbTipo.getSelectedIndex()) {
            case 0: {
                preencher.PreencherJtableGenerico(jTbConsulta,
                        new String[]{"id_cat_produto", "nome", "descricao"},
                        daoproduto.consultageral());
                break;
            } 
            case 1: {
                modproduto.setIdproduto(Integer.parseInt(jTFPesquisarProduto.getText()));
                preencher.PreencherJtableGenerico(jTbConsulta,
                        new String[]{"id_cat_produto", "nome", "descricao"},
                        daoproduto.consultaid(modproduto));
                break;
            }
            case 2: {
                modproduto.setNome(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_cat_produto", "nome", "descricao"},
                        daoproduto.consultanome(modproduto));
                break;
            }
            case 3: {
                modproduto.setDescricao(jTFPesquisarProduto.getText());
                preencher.PreencherJtableGenerico(jTbConsulta,
                       new String[]{"id_cat_produto", "nome", "descricao"},
                        daoproduto.consultadescricao(modproduto));
                break;
            }
        }
    }//GEN-LAST:event_jBPesquisarProdutoActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        // TODO add your handling code here:
          if (jTFNomeProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Descrição Obrigatoria");
            jTFNomeProduto.grabFocus();
            return;
        } else {

            setcomp();
            if (estado == Rotinas.INCLUIR) {
                daoproduto.incluir(modproduto);
            } else if (estado == Rotinas.ALTERAR) {
                daoproduto.alterar(modproduto);
            }
            getcomp();
            estadobotoes(0);
        }
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jTFPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarProdutoActionPerformed

    private void jTbConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbConsultaMouseClicked
        
        if (evt.getClickCount() == 2) {
          int linha = jTbConsulta.getSelectedRow();
          
          String codigo = (String) jTbConsulta.getValueAt(linha, 0);
          modproduto.setIdproduto(Integer.parseInt(codigo));
          daoproduto.retornadados(modproduto);
          getcomp();
          jTbPainel.setSelectedIndex(0);
      }
    }//GEN-LAST:event_jTbConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBAlterar;
    private javax.swing.JToggleButton jBCancelar;
    private javax.swing.JToggleButton jBExcluir;
    private javax.swing.JToggleButton jBGravar;
    private javax.swing.JToggleButton jBNovo;
    private javax.swing.JToggleButton jBPesquisarProduto;
    private javax.swing.JComboBox<String> jCbTipo;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDrecricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPCasulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigoProduto;
    private javax.swing.JTextField jTFDescricaoProduto;
    private javax.swing.JTextField jTFNomeProduto;
    private javax.swing.JTextField jTFPesquisarProduto;
    private javax.swing.JTable jTbConsulta;
    private javax.swing.JTabbedPane jTbPainel;
    // End of variables declaration//GEN-END:variables

    private void estadobotoes(int situacao) {
      if (situacao == 0) {
            jBNovo.setEnabled(true);
            jBAlterar.setEnabled(true);
            jBExcluir.setEnabled(true);
            jBGravar.setEnabled(false);
            jBCancelar.setEnabled(false);
        } else {
            jBNovo.setEnabled(false);
            jBAlterar.setEnabled(false);
            jBExcluir.setEnabled(false);
            jBGravar.setEnabled(true);
            jBCancelar.setEnabled(true);
        }
    }

    private void setcomp() {
       if (estado == Rotinas.ALTERAR) {
            modproduto.setIdproduto(Integer.parseInt(jTFCodigoProduto.getText()));
        }
        modproduto.setNome(jTFNomeProduto.getText());
        modproduto.setDescricao(jTFDescricaoProduto.getText());
       
    }

    private void getcomp() {
        jTFCodigoProduto.setText(Integer.toString(modproduto.getIdproduto()));
        jTFNomeProduto.setText(modproduto.getNome());
        jTFDescricaoProduto.setText(modproduto.getDescricao());
      
    }
}
